backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img # Media files will be stored in the repo under images/uploads
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "settings"
    label: "Settings"
    files:
      - file: "src/data/settings.yml"
        label: "Site settings"
        name: "sitesettings"
        fields:
          - {
              label: "Social Media",
              name: "socialmedia",
              widget: "list",
              field: { label: URL, name: url, widget: string },
            }
          - {
              label: "Address Line",
              name: "addressLine",
              widget: "list",
              field: { label: Line, name: line, widget: string },
            }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone Number", name: "phoneNumber", widget: "string" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about-us.md"
        label: "About Us Page"
        name: "about-us"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-us",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image (), name: image, widget: image }
          - { label: Mobile Image (), name: mobileImage, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: CategoryPitch,
              name: categorypitch,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Text, name: text, widget: text },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: About us,
              name: aboutUs,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Text,
                    name: text,
                    widget: list,
                    fields:
                      [{ label: Paragraph, name: paragraph, widget: text }],
                  },
                ],
            }
          - {
              label: Our team,
              name: ourTeam,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Text,
                    name: text,
                    widget: list,
                    fields:
                      [{ label: Paragraph, name: paragraph, widget: text }],
                  },
                ],
            }
          - {
              label: Profiles,
              name: profiles,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Name, name: name, widget: string },
                  { label: Blurb, name: blurb, widget: text },
                ],
            }
      - file: "src/pages/our-clients.md"
        label: "Our Clients Page"
        name: "ourClients"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "ourClients",
            }
      - file: "src/pages/services.md"
        label: "Services Page"
        name: "services"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "services",
            }
          - {
              label: "Section",
              name: "section",
              widget: list,
              types:
                [
                  {
                    label: "Image",
                    name: "image",
                    widget: object,
                    fields: [{ label: Path, name: path, widget: image }],
                  },
                  {
                    label: "Text",
                    name: "text",
                    widget: object,
                    fields: [{ label: Words, name: words, widget: text }],
                  },
                ],
            }
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image (), name: image, widget: image }
          - { label: Mobile Image (), name: mobileImage, widget: image }
          - {
              label: CategoryPitch,
              name: categorypitch,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Text, name: text, widget: text },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: "Why pick us?",
              name: whyPickUsList,
              widget: list,
              fields: [{ label: Reason, name: reason, widget: string }],
            }
          - {
              label: Introduction,
              name: introduction,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Text,
                    name: text,
                    widget: list,
                    fields:
                      [{ label: Paragraph, name: paragraph, widget: text }],
                  },
                ],
            }
