backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img # Media files will be stored in the repo under images/uploads
public_folder: /img

collections:
  - name: "settings"
    label: "Settings"
    files:
      - file: "src/data/settings.yml"
        label: "Site settings"
        name: "sitesettings"
        fields:
          - {
              label: "Social Media",
              name: "socialmedia",
              widget: "list",
              field: { label: Company, name: company, widget: string },
            }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/sitewide.md"
        label: "Site Data"
        name: "sitewide"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "sitewide",
            }
          - { label: Title, name: title, widget: string }
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: CategoryPitch,
              name: categorypitch,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Text, name: text, widget: text },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Introduction,
              name: introduction,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Text,
                    name: text,
                    widget: list,
                    fields:
                      [{ label: Paragraph, name: paragraph, widget: text }],
                  },
                ],
            }
      - file: "src/pages/test.md"
        label: "Test Page"
        name: "test-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
